### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by jr0dd** [jr0dd/home-ops#18]
- [x] move grafana dashboards to chart
- [x] test/configure homer
- [x] install thanos 
- [x] Add podmonitor for qbittorrent-exporter
- [x] split-horizon dns
- [x] get minio-operator working despite of the broken official chart

**Comment by jr0dd** [comment]
Using the official regular minio chart until their operator chart matures a bit more, because there are some disconnects between the components.
